### ISSUE TITLE
non-stdin golang formatter

### ISSUE THREAD

**Issue by malinka-2233** [elentok/format-on-save.nvim#1]
hey! thank you for creating this plugin. In reddit comments you asked about formatters that do not support stdin. There is one that i use - https://github.com/incu6us/goimports-reviser
It had to be set up using temp files in null-ls. (and it is kinda broken for it right now)

**Comment by elentok** [comment]
Thanks @malinka-2233!

I just submitted a commit that adds support and added an example in the readme file specific to goimports-reviser.
