### ISSUE TITLE
Formating deletes all contents within the file

### ISSUE THREAD

**Issue by Redhawk18** [elentok/format-on-save.nvim#23]
I revisited my config and got it triggering with the alejandra shell formatter. They trigger but they delete all the contents of the file when I save it. I'm not sure what causes this? Maybe the plugin expects the formatter to print out the new formatted code?

**Comment by faergeek** [comment]
>Maybe the plugin expects the formatter to print out the new formatted code?

Yes, that's exactly what this plugin expects
