### ISSUE TITLE
Make shell formatter cmd optionally a function

### ISSUE THREAD

**Issue by jackfranklin** [elentok/format-on-save.nvim#7]
Sometimes I want to configure a shell formatter with slightly different arguments depending on the buffer that it is formatting.

Because for a shell formatter right now I have to define the cmd up front, I cannot dynamically change this (I don't think) at format time.

Would you be open to `cmd` being either a table, or a function that is called at format time? I would be happy to do the work and send you a PR. Thanks!

**Comment by elentok** [comment]
Hi Jack :-)

Thanks! Sounds like a useful feature, it's pretty straight forward so I already implemented it (see [this commit][1]), does it cover your scenario?


[1]: https://github.com/elentok/format-on-save.nvim/commit/c491215d4e04a6aeef7cc2b57da5c965bfaab190

**Comment by jackfranklin** [comment]
Looks like it does! Thank you
