### ISSUE TITLE
Enable formatters conditionally based on presence of files

### ISSUE THREAD

**Issue by jackfranklin** [elentok/format-on-save.nvim#8]
A feature of null-ls I really liked was the ability to conditionally enable a formatter:

```
      null_ls.builtins.formatting.eslint_d.with({
        condition = function(utils)
          return utils.root_has_file({ ".eslintrc.js", ".eslintrc.cjs", ".eslintrc.mjs" })
        end,
      }),
```

Would you consider something similar? Again I am happy to do the work and make PRs :)

**Comment by elentok** [comment]
Hi Jack,

I actually already have this functionality for eslint_d (see [formatters.lazy_eslint_d_fix][1]), but you gave me an idea to extract it to a helper that creates a lazy formatter that only returns a formatter if a certain file exists (see [commit][2]).

There's a slight difference here where it doesn't only look in the root directory, it starts from the current file and goes up until it finds a file that matches the provided patterns.

What do you think?


[1]: https://github.com/elentok/format-on-save.nvim/blob/bb51749fb5f46c5941b2ccceaa651989b390111f/lua/format-on-save/formatters.lua#L57
[2]: https://github.com/elentok/format-on-save.nvim/commit/bb51749fb5f46c5941b2ccceaa651989b390111f

**Comment by jackfranklin** [comment]
That approach works for me! At what directory does the code stop checking for matches? I would expect that it stops at the root directory (by which I mean whatever Vim thinks `cwd` is), but from the code I think it might work its way all the way up to `/`. This seems maybe wasteful to me, but perhaps others would rely on this, so feel free to ignore me :)

**Comment by elentok** [comment]
That's an excellent point! Currently the code does go all the way up to "/" and I'm not sure where it should stop. I thought about adding an option to `formatters.if_file_exists` named `root` or something like and then it can be configurable per-formatter (e.g. `cwd`, `git`, `node-package`).

To make this fully customizable it'll just accept a function that will return the root dir and then I'll add a `root-finders.lua` file with several built-in root finders.

What do you think?

**Comment by jackfranklin** [comment]
Yeah that SGTM - I think either Vim's cwd or the git root would be the most useful options. Thanks for all your work on this!
